# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagefromsky',
            options={'ordering': ['date'], 'verbose_name': 'СообщенияИзКосмоса', 'verbose_name_plural': 'СообщенииИзКосмоса'},
        ),
        migrations.AlterField(
            model_name='messagefromsky',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='messagefromsky',
            name='seen',
            field=models.BooleanField(verbose_name='Прочитано'),
        ),
        migrations.AlterField(
            model_name='messagefromsky',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
